<?php
/**
 * @file
 * Install, update and uninstall functions for the blog module.
 */

/**
 * Implements hook_install().
 */
function node_revision_delete_install() {
  // Ensure the blog node type is available.
  node_types_rebuild();
  $types = node_type_get_types();
  variable_set('node_revision_delete_number',50);
}

/**
 * Implements hook_uninstall().
 */
function node_revision_delete_uninstall() {
  variable_del('node_revision_delete_number');
}
