node_revision_delete.settings:
  type: config_object
  label: 'Node Revision Delete settings'
  mapping:
    node_revision_delete_cron:
      type: integer
      label: 'Number of revisions to remove in each cron run' 
    node_revision_delete_last_execute:
      type: integer
      label: 'Last time that the node revision delete was made' 
    node_revision_delete_time:
      type: string
      label: 'Frequency with which to delete revisions while cron is running'
    node_revision_delete_track:
      type: sequence
      label: 'Configuration for each content_type'
      sequence:
        type: mapping
        mapping:
          revisions_to_keep:
            type: integer
            label: 'Maximun number of revisions to keep'
          when_to_delete:
            type: integer
            label: 'Number of inactivity months to wait for delete a revision'
          minimun_age_to_delete:
            type: integer
            label: 'Minimum age in months of revision to delete'
